#!/usr/bin/python

# Text To Speech with Python, powered by ISpeech (http://www.ispeech.org)
# Based on a bash script from Mikey Life (see http://karotz.mikey-life.com/www/compte/astuces/ > TTS) 
# Save this file as "tts" in /www/cgi-bin, and delete tts.inc.
# Provided by FreeRabbits.nl

import cgi
import os
import sys
import urllib
import md5
import simplejson as json

def RunCommand(cmd):
    return os.system(cmd)

def IsSleeping():
    return os.path.isfile("/tmp/karotz.sleep") or os.path.isfile("/usr/openkarotz/Run/karotz.sleep")

def PlayMP3(mp3file):
    if not IsSleeping():
        cmd = "/usr/bin/madplay " + mp3file + " >/dev/null 2>&1"
        return os.system(cmd)

# Main program
voices = [ "eurfrenchfemale", "eurfrenchmale", "cafrenchfemale", "cafrenchmale", "usenglishfemale", "usenglishmale", "ukenglishfemale", "ukenglishmale", "eurgermanfemale", "eurgermanmale", "euritalianfemale", "euritalianmale", "eurspanishfemale", "eurspanishmale", "eurdutchfemale" ]
apiKey = "api-key-goes-here"
md5Hash = ""
voice = 0
voicename = "eurfrenchfemale"
cached = False
cmd = ""
result = 1
fields = cgi.FieldStorage()

if "voice" in fields:
    voice = int(fields["voice"].value)
    voicename = voices[voice - 1]	

if "text" in fields:
    text = fields["text"].value
    md5Hash = md5.new(voicename + text).hexdigest()
    mp3FileName = "/tmp/" + md5Hash + ".mp3"
    cached = os.path.isfile(mp3FileName)
    if not cached:
        params = urllib.urlencode({"apikey": apiKey, "action": "convert", "voice": voicename, "speed": 0, "pitch": 100, "text": text})
        baseUrl = "http://api.ispeech.org/api/rest"
        cmd = "wget -q -O %(mp3)s \"%(url)s?%(params)s\"" % { "mp3": mp3FileName, "url": baseUrl, "params": params }
        result = RunCommand(cmd)
    if os.path.isfile(mp3FileName):
        result = PlayMP3(mp3FileName)

# Create the JSON object
data = {}
data["return"] = (result == 0)
data["id"] = md5Hash
data["played"] = (result == 0)
data["cache"] = cached
data["voice"] = voicename

# Write Output Response
print "Server: OpenKarotz WebServer 1.0"
print "Connection: close"
print "Accept-Ranges: bytes"
print "Content-type: text/plain"
print "Access-Control-Allow-Origin: *"
print
print json.dumps(data)
