#!/usr/bin/python

# Text To Speech with Python, powered by ResponsiveVoice (https://responsivevoice.org)
# Based on a bash script from Mikey Life (see http://karotz.mikey-life.com/www/compte/astuces/ > TTS) 
# Save this file as "tts" in /www/cgi-bin, and delete tts.inc.
# Also update "voice_list" with the corresponding voicenames.
# Provided by FreeRabbits.nl

import cgi
import os
import sys
import urllib
import md5
import simplejson as json

def RunCommand(cmd):
    return os.system(cmd)

def IsSleeping():
    return os.path.isfile("/tmp/karotz.sleep") or os.path.isfile("/usr/openkarotz/Run/karotz.sleep")

def PlayMP3(mp3file):
    if not IsSleeping():
        cmd = "/usr/bin/madplay " + mp3file + " >/dev/null 2>&1"
        return os.system(cmd)

# Main program
voice = 0
voices = [ "fr", "fr", "fr", "fr", "en-US", "en-US", "en-GB", "en-GB", "de", "de", "it", "it", "es", "es", "nl", "nl", "af", "af", "sq", "sq", "ar", "ar", "hy", "hy", "bs", "bs", "pt-BR", "pt-BR", "hr", "hr", "cs", "cs", "da", "da", "en-AU", "en-AU", "eo", "eo", "fi", "fi", "el", "el", "ht", "ht", "hi", "hi", "hu", "hu", "is", "is", "id", "id", "ja", "ja", "ko", "ko", "la", "la", "no", "no", "pl", "pl", "pt-PT", "pt-PT", "ro", "ro", "ru", "ru", "sr", "sr", "sh", "sh", "sk", "sk", "sw", "sw", "sv", "sv", "ta", "ta", "th", "th", "tr", "tr", "vi", "vi", "cy", "cy" ]
voicelanguage = "fr"
voicegender = "female"
md5Hash = ""
cached = False
cmd = ""
result = 1
fields = cgi.FieldStorage()

if "voice" in fields:
    voice = int(fields["voice"].value)
    voicelanguage = voices[voice - 1]
    voicegender = (voice % 2 == 0) and "female" or "male"

if "text" in fields:
    text = fields["text"].value
    md5Hash = md5.new(voicelanguage + voicegender + text).hexdigest()
    mp3FileName = "/tmp/" + md5Hash + ".mp3"
    cached = os.path.isfile(mp3FileName)
    if not cached:
        params = urllib.urlencode({"sv": "g1", "pitch": 0.5, "rate": 0.5, "vol": 1, "tl": voicelanguage, "gender": voicegender, "t": text})
        baseUrl = "http://code.responsivevoice.org/getvoice.php"
        cmd = "wget -q -O %(mp3)s \"%(url)s?%(params)s\"" % { "mp3": mp3FileName, "url": baseUrl, "params": params }
        result = RunCommand(cmd)
    if os.path.isfile(mp3FileName):
        result = PlayMP3(mp3FileName)

# Create the JSON object
data = {}
data["return"] = (result == 0)
data["id"] = md5Hash
data["played"] = (result == 0)
data["cache"] = cached
data["voicelanguage"] = voicelanguage
data["voicegender"] = voicegender

# Write Output Response
print "Server: OpenKarotz WebServer 1.0"
print "Connection: close"
print "Accept-Ranges: bytes"
print "Content-type: text/plain"
print "Access-Control-Allow-Origin: *"
print
print json.dumps(data)
