#!/bin/bash

# New list with Voices. Save this file as voice_list in /www/cgi-bin
# This list is displayed in the web UI, in tab 'TTS'

source /www/cgi-bin/utils.inc
 
VL='{ "voices": [ 
    { "id":"1","lang":"fr Female"},
    { "id":"2","lang":"fr Male"},
    { "id":"3","lang":"ca Female"},
    { "id":"4","lang":"ca Male"},
    { "id":"5","lang":"us Female"},
    { "id":"6","lang":"us Male"},
    { "id":"7","lang":"uk Female"},
    { "id":"8","lang":"uk Male"},
    { "id":"9","lang":"de Female"},
    { "id":"10","lang":"de Male"},
    { "id":"11","lang":"it Female"},
    { "id":"12","lang":"it Male"},
    { "id":"13","lang":"spain Female"},
    { "id":"14","lang":"spain Male"},
    { "id":"15","lang":"dutch Female"}
], "return":"0" }'
 
SendResponse "$VL"
